name: 'manual-test'
on:
  workflow_dispatch:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          issue-title: This is a test ticket
          issue-body: This is the body of our test ticket
          team-name: Tickets
          starting-status: Open
